// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// linprogPD2C
Rcpp::List linprogPD2C(arma::vec x, arma::mat A, arma::vec b, double epsilon, double pdtol, int pdmaxiter);
RcppExport SEXP clime2_linprogPD2C(SEXP xSEXP, SEXP ASEXP, SEXP bSEXP, SEXP epsilonSEXP, SEXP pdtolSEXP, SEXP pdmaxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type pdtol(pdtolSEXP);
    Rcpp::traits::input_parameter< int >::type pdmaxiter(pdmaxiterSEXP);
    __result = Rcpp::wrap(linprogPD2C(x, A, b, epsilon, pdtol, pdmaxiter));
    return __result;
END_RCPP
}
